---
- name: Install Apt-Transport-https
  apt: name=apt-transport-https state=present
  tags:
    - docker
    - docker-host

- name: Install apt ca-certs
  apt: name=ca-certificates state=present
  tags:
    - docker
    - docker-host

- name: Add the GPG Key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
     - docker-host

- name: add the Docker repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  register: docker_repo
  tags:
     - docker-host

- name: update the apt cache
  apt: update_cache=yes
  tags:
    - docker
    - docker-host

- name: Enable ipv4 forwarding
  sysctl: name=net.ipv4.conf.default.forwarding value=1 state=present
  tags:
    - docker
    - docker-host

- name: Enable ipv6 forwarding
  sysctl: name=net.ipv6.conf.default.forwarding value=1 state=present
  tags:
    - docker
    - docker-host

- name: remove any old Docker versions
  apt:
    name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']
    state: absent
  tags:
     - docker-host

- name: Install Docker
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present
  tags:
     - docker-host

- name: Install Docker-Compose
  apt: name=docker-compose state=present
  tags:
     - docker-host

- name: Make sure the docker py lib is installed
  pip:
    name: ['docker']
    state: present
  tags:
    - docker-host

- name: create the /apps directory
  file:
    path: /apps
    state: directory
    mode: 0755
  tags:
    - docker
    - docker-host

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    group: "docker"
    append: yes
