---
- name: Install Apt-Transport-https
  apt: name=apt-transport-https state=present
  tags:
    - docker
    - docker-host

- name: Install apt ca-certs
  apt: name=ca-certificates state=present
  tags:
    - docker
    - docker-host

- name: Enable ipv4 forwarding
  sysctl: name=net.ipv4.conf.default.forwarding value=1 state=present
  tags:
    - docker
    - docker-host

- name: Enable ipv6 forwarding
  sysctl: name=net.ipv6.conf.default.forwarding value=1 state=present
  tags:
    - docker
    - docker-host

- name: Install Containerd
  apt:
    name: ['containerd.io']
    state: present
  tags:
     - docker-host

- name: Re-enable the cri plugin and SystemdCgroup for containerd
  template: src=config.toml dest=/etc/containerd/config.toml
  register: containerd_config
  tags:
    - docker-host

- name: Restart containerd if needed
  when: containerd_config is changed
  service: 
    name: containerd
    state: restarted
  tags:
    - docker-host

- name: create the /apps directory
  file:
    path: /apps
    state: directory
    mode: 0755
  tags:
    - docker
    - docker-host

